# Generated by Django 4.0 on 2023-03-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=70, verbose_name='Bairro')),
            ],
            options={
                'ordering': ['nome_bairro'],
            },
        ),
        migrations.CreateModel(
            name='Defesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=12, verbose_name='Protocolo de defesa')),
                ('entrada_protocolo', models.DateField(verbose_name='Data de entrada')),
                ('quem', models.CharField(max_length=100, verbose_name='Nome de quem protocoloou')),
                ('grau', models.CharField(choices=[('PROPRIO', 'PROPRIO'), ('CORRESPONSAVEL', 'CORRESPONSAVEL'), ('OUTROS', 'OUTROS')], max_length=50, verbose_name='Grau de relação')),
                ('prazo_manifesto', models.DateField(blank=True, verbose_name='Prazo de manifesto')),
            ],
            options={
                'ordering': ['prazo_manifesto'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=25, verbose_name='Estado')),
                ('sigla_estado', models.CharField(max_length=2, verbose_name='Sigla do Estado')),
            ],
            options={
                'ordering': ['nome_estado'],
            },
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fiscal', models.CharField(max_length=36)),
                ('matricula_fiscal', models.CharField(max_length=5)),
                ('nivel', models.CharField(choices=[('FISCAL SANITÁRIO I', 'FISCAL SANITÁRIO I'), ('FISCAL SANITÁRIO II', 'FISCAL SANITÁRIO II')], max_length=19)),
                ('primeiro_nome', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['nome_fiscal'],
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_logradouro', models.CharField(max_length=80, verbose_name='Logradouro')),
                ('tipo', models.CharField(choices=[('RUA', 'RUA'), ('AVENIDA', 'AVENIDA'), ('PRAÇA', 'PRAÇA'), ('BECO', 'BECO'), ('ALAMEDA', 'ALAMEDA'), ('ESTRADA', 'ESTRADA'), ('LARGO', 'LARGO'), ('PASSAGEM', 'PASSAGEM'), ('PASSARELA', 'PASSARELA'), ('RODOVIA', 'RODOVIA'), ('SETOR', 'SETOR'), ('TRAVESSA', 'TRAVESSA'), ('TREVO', 'TREVO')], max_length=22)),
                ('cep', models.CharField(max_length=13, verbose_name='CEP')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.bairro')),
            ],
            options={
                'ordering': ['nome_logradouro'],
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proprietario', models.CharField(max_length=55)),
                ('numero_proprietario', models.CharField(max_length=20, null=True, verbose_name='Número')),
                ('complemento_proprietario', models.CharField(blank=True, max_length=40, null=True, verbose_name='Complemento')),
                ('nome_coresponsavel_1', models.CharField(max_length=60, null=True)),
                ('logradouro_proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.logradouro')),
            ],
            options={
                'ordering': ['nome_proprietario'],
            },
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.CharField(max_length=18, unique=True, verbose_name='Inscrição imobiliária')),
                ('numero_terreno', models.CharField(max_length=20, verbose_name='Número do terreno')),
                ('complemento_terreno', models.CharField(blank=True, max_length=40, null=True, verbose_name='Complemento')),
                ('lote', models.CharField(max_length=10)),
                ('quadra', models.CharField(max_length=8)),
                ('area', models.FloatField()),
                ('numero_correspondencia', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento_correspondencia', models.CharField(blank=True, max_length=40, null=True, verbose_name='Complemento')),
                ('tipo_de_imovel', models.CharField(choices=[('TERRENO', 'TERRENO'), ('CASA ABANDONADA', 'CASA ABANDONADA')], max_length=22)),
                ('logradouro_correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logradouro_correspondencia', to='cadastros.logradouro', verbose_name='Endereço de correspondência')),
                ('logradouro_terreno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logradouro_terreno', to='cadastros.logradouro', verbose_name='Logradouro do terreno')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.proprietario', verbose_name='Proprietário')),
            ],
            options={
                'ordering': ['inscricao'],
            },
        ),
        migrations.CreateModel(
            name='Reinspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao2', models.DateField(verbose_name='Data da reinspeção')),
                ('horario_inspecao2', models.TimeField(verbose_name='Horário de reinspeção')),
                ('foto_inspecao_2', models.FileField(upload_to='fotos/', verbose_name='Foto da reinspeção')),
                ('data_manifesto', models.DateField(verbose_name='Data do manifesto')),
                ('situacao', models.CharField(choices=[('1', 'Defendeu e limpou'), ('2', 'Não defendeu e limpou'), ('3', 'Não defendeu e não limpou'), ('4', 'Defendeu fora do prazo e limpou')], max_length=25, verbose_name='Situação')),
                ('defesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.defesa', verbose_name='Defesa')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=12)),
                ('solicitante_protocolo', models.CharField(choices=[('PESSOA FÍSICA', 'PESSOA FÍSICA'), ('CORPO DE BOMBEIROS', 'CORPO DE BOMBEIROS'), ('MINISTÉRIO PÚBLICO', 'MINISTÉRIO PÚBLICO'), ('PREFEITURA', 'PREFEITURA'), ('ORDEM JUDICIAL', 'ORDEM JUDICIAL'), ('OUTRAS INSTITUIÇÕES', 'OUTRAS INSTITUIÇÕES'), ('VEREADORES', 'VEREADORES')], max_length=40)),
                ('descricao_protocolo', models.CharField(max_length=250)),
                ('ouvidoria', models.CharField(blank=True, max_length=10, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=660, null=True)),
                ('status_protocolo', models.CharField(choices=[('ABERTO', 'ABERTO'), ('PENDENTE', 'PENDENTE'), ('AGUARDANDO EDITAL', 'AGUARDANDO EDITAL'), ('AGUARDANDO RETORNO DA AR', 'AGUARDANDO RETORNO DA AR'), ('FINALIZADO', 'FINALIZADO'), ('INSPECIONADO', 'INSPECIONADO'), ('PRAZO DE DEFESA AR', 'PRAZO DE DEFESA AR'), ('PRAZO DE DEFESA EDITAL', 'PRAZO DE DEFESA EDITAL'), ('PRAZO PARA JULGAMENTO AR', 'PRAZO PARA JULGAMENTO AR'), ('PRAZO DE JULGAMENTO EDITAL', 'PRAZO DE JULGAMENTO EDITAL')], max_length=26)),
                ('entrada_protocolo', models.DateField()),
                ('encerramento_protocolo', models.DateField(blank=True, null=True)),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.logradouro')),
            ],
            options={
                'ordering': ['protocolo'],
            },
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao1', models.DateField(verbose_name='Data da inspeção')),
                ('horario_inspecao1', models.TimeField(verbose_name='Horário de inspeção')),
                ('foto_inspecao_1', models.FileField(upload_to='fotos/', verbose_name='Foto da inspeção')),
                ('data_relatorio1', models.DateField(verbose_name='Data do relatório da inspeção')),
                ('produtidade_inspecao', models.DateField(blank=True, null=True, verbose_name='Qual o mês (data) da produtividade?')),
                ('limpo', models.CharField(blank=True, choices=[('LIMPO', 'LIMPO'), ('RAZOAVEL', 'RAZOÁVEL')], max_length=15, null=True, verbose_name='Está limpo')),
                ('mato', models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Mato alto')),
                ('pneu', models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Pneu(s)')),
                ('entulho', models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Entulho(s)')),
                ('material', models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Material(is)')),
                ('lixo', models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Lixo(s)')),
                ('movel', models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Móvel(is)')),
                ('carcaca', models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Carcaça')),
                ('outro', models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Outros')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.fiscal')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.protocolo')),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.terreno')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rastreio_infracao', models.CharField(blank=True, max_length=13, null=True, verbose_name='Código de rastreio')),
                ('status_rastreio', models.CharField(blank=True, choices=[('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('MUDOU-SE', 'MUDOU-SE'), ('ENDEREÇO INSUFICIENTE', 'ENDEREÇO INSUFICIENTE'), ('NÃO EXISTE O NÚMERO', 'NÃO EXISTE O NÚMERO'), ('DESCONHECIDO', 'DESCONHECIDO'), ('RECUSADO', 'RECUSADO'), ('OUTROS', 'OUTROS'), ('NÃO PROCURADO', 'NÃO PROCURADO'), ('AUSENTE', 'AUSENTE'), ('FALECIDO', 'FALECIDO'), ('ENVIADO POR E-MAIL', 'ENVIADO POR E-MAIL'), ('ENVIADO POR WHATSAPP', 'ENVIADO POR WHATSAPP')], max_length=22, null=True, verbose_name='Status devolução Correios')),
                ('data_entrega_autuacao', models.DateField(blank=True, null=True, verbose_name='Data da entrega do Auto de infração')),
                ('prazo_defesa', models.DateField(blank=True, null=True, verbose_name='Prazo de defesa')),
                ('nome_recebedor', models.CharField(blank=True, max_length=60, null=True, verbose_name='Quem recebeu?')),
                ('numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numero_format_ano', models.CharField(blank=True, max_length=9, null=True, verbose_name='Auto de Infração')),
                ('data_auto', models.DateField(verbose_name='Data do Auto de Infração')),
                ('protocolo_defesa', models.CharField(blank=True, max_length=12, null=True, verbose_name='Protocolo de defesa')),
                ('entrada_protocolo', models.DateField(blank=True, null=True, verbose_name='Data de entrada')),
                ('quem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de quem protocoloou')),
                ('grau', models.CharField(blank=True, choices=[('PROPRIO', 'PROPRIO'), ('CORRESPONSAVEL', 'CORRESPONSAVEL'), ('OUTROS', 'OUTROS')], max_length=50, null=True, verbose_name='Grau de relação')),
                ('prazo_manifesto', models.DateField(blank=True, null=True, verbose_name='Prazo de manifesto')),
                ('data_inspecao2', models.DateField(blank=True, null=True, verbose_name='Data da reinspeção')),
                ('horario_inspecao2', models.TimeField(blank=True, null=True, verbose_name='Horário de reinspeção')),
                ('foto_inspecao_2', models.FileField(blank=True, upload_to='fotos/', verbose_name='Foto da reinspeção')),
                ('data_manifesto', models.DateField(blank=True, null=True, verbose_name='Data do manifesto')),
                ('julgamento', models.DateField(blank=True, null=True, verbose_name='Data do julgamento')),
                ('situacao', models.CharField(blank=True, choices=[('1', 'Defendeu e limpou'), ('2', 'Não defendeu e limpou'), ('3', 'Não defendeu e não limpou'), ('4', 'Manifesto e julgamento fora do sistema'), ('5', 'Defendeu após o prazo e limpou'), ('6', 'Não recebeu e limpou'), ('7', 'Edital'), ('8', 'Não defendeu e não limpou via Edital'), ('9', 'Não defendeu e limpou via Edital')], max_length=25, null=True, verbose_name='Situação')),
                ('rastreio_julgamento', models.CharField(blank=True, max_length=13, null=True, verbose_name='Código de rastreio do julgamento')),
                ('status_rastreio_julgamento', models.CharField(blank=True, choices=[('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('MUDOU-SE', 'MUDOU-SE'), ('ENDEREÇO INSUFICIENTE', 'ENDEREÇO INSUFICIENTE'), ('NÃO EXISTE O NÚMERO', 'NÃO EXISTE O NÚMERO'), ('DESCONHECIDO', 'DESCONHECIDO'), ('RECUSADO', 'RECUSADO'), ('OUTROS', 'OUTROS'), ('NÃO PROCURADO', 'NÃO PROCURADO'), ('AUSENTE', 'AUSENTE'), ('FALECIDO', 'FALECIDO'), ('ENVIADO POR E-MAIL', 'ENVIADO POR E-MAIL'), ('ENVIADO POR WHATSAPP', 'ENVIADO POR WHATSAPP')], max_length=22, null=True, verbose_name='Status devolução julgamento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('data_entrega_julgamento', models.DateField(blank=True, null=True, verbose_name='Data da entrega do julgamento')),
                ('produtividade_infracao', models.DateField(blank=True, null=True, verbose_name='Qual o mês (data) da produtividade?')),
                ('produtividade_manifesto', models.DateField(blank=True, null=True, verbose_name='Qual o mês (data) da produtividade do manifesto?')),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.inspecao', verbose_name='Inspeção')),
            ],
        ),
        migrations.AddField(
            model_name='defesa',
            name='infracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.infracao', verbose_name='Auto de Infração'),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estado')),
            ],
            options={
                'ordering': ['nome_cidade'],
            },
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade'),
        ),
    ]
