# Generated by Django 4.0 on 2022-07-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_alter_infracao_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='status_rastreio',
            field=models.CharField(blank=True, choices=[('NÃO ENVIADO AINDA', 'NÃO ENVIADO AINDA'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('MUDOU-SE', 'MUDOU-SE'), ('ENDEREÇO INSUFICIENTE', 'ENDEREÇO INSUFICIENTE'), ('NÃO EXISTE O NÚMERO', 'NÃO EXISTE O NÚMERO'), ('DESCONHECIDO', 'DESCONHECIDO'), ('RECUSADO', 'RECUSADO'), ('OUTROS', 'OUTROS'), ('NÃO PROCURADO', 'NÃO PROCURADO'), ('AUSENTE', 'AUSENTE'), ('FALECIDO', 'FALECIDO'), ('ENVIADO VIA E-MAIL', 'ENVIADO VIA E-MAIL')], max_length=22, null=True, verbose_name='Status devolução Correios'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='status_rastreio_julgamento',
            field=models.CharField(blank=True, choices=[('NÃO ENVIADO AINDA', 'NÃO ENVIADO AINDA'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('MUDOU-SE', 'MUDOU-SE'), ('ENDEREÇO INSUFICIENTE', 'ENDEREÇO INSUFICIENTE'), ('NÃO EXISTE O NÚMERO', 'NÃO EXISTE O NÚMERO'), ('DESCONHECIDO', 'DESCONHECIDO'), ('RECUSADO', 'RECUSADO'), ('OUTROS', 'OUTROS'), ('NÃO PROCURADO', 'NÃO PROCURADO'), ('AUSENTE', 'AUSENTE'), ('FALECIDO', 'FALECIDO'), ('ENVIADO VIA E-MAIL', 'ENVIADO VIA E-MAIL')], max_length=22, null=True, verbose_name='Status devolução julgamento'),
        ),
    ]
