# Generated by Django 4.0 on 2022-10-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_alter_infracao_status_rastreio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='limpo',
            field=models.CharField(blank=True, choices=[('LIMPO', 'LIMPO'), ('RAZOAVEL', 'RAZOÁVEL')], max_length=15, null=True, verbose_name='Está limpo'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='data_auto',
            field=models.DateField(verbose_name='Data do Auto de Infração'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='inspecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.inspecao', verbose_name='Inspeção'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Defendeu e limpou'), ('2', 'Não defendeu e limpou'), ('3', 'Não defendeu e não limpou'), ('4', 'Manifesto e julgamento fora do sistema'), ('5', 'Defendeu após o prazo e limpou'), ('6', 'Não recebeu e limpou'), ('7', 'Edital')], max_length=25, null=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='status_rastreio',
            field=models.CharField(blank=True, choices=[('NÃO ENVIADO AINDA', 'NÃO ENVIADO AINDA'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('MUDOU-SE', 'MUDOU-SE'), ('ENDEREÇO INSUFICIENTE', 'ENDEREÇO INSUFICIENTE'), ('NÃO EXISTE O NÚMERO', 'NÃO EXISTE O NÚMERO'), ('DESCONHECIDO', 'DESCONHECIDO'), ('RECUSADO', 'RECUSADO'), ('OUTROS', 'OUTROS'), ('NÃO PROCURADO', 'NÃO PROCURADO'), ('AUSENTE', 'AUSENTE'), ('FALECIDO', 'FALECIDO')], max_length=22, null=True, verbose_name='Status devolução Correios'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='status_rastreio_julgamento',
            field=models.CharField(blank=True, choices=[('NÃO ENVIADO AINDA', 'NÃO ENVIADO AINDA'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('MUDOU-SE', 'MUDOU-SE'), ('ENDEREÇO INSUFICIENTE', 'ENDEREÇO INSUFICIENTE'), ('NÃO EXISTE O NÚMERO', 'NÃO EXISTE O NÚMERO'), ('DESCONHECIDO', 'DESCONHECIDO'), ('RECUSADO', 'RECUSADO'), ('OUTROS', 'OUTROS'), ('NÃO PROCURADO', 'NÃO PROCURADO'), ('AUSENTE', 'AUSENTE'), ('FALECIDO', 'FALECIDO')], max_length=22, null=True, verbose_name='Status devolução julgamento'),
        ),
    ]
