# Generated by Django 4.0 on 2022-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_inspecao_limpo_alter_infracao_data_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Defendeu e limpou'), ('2', 'Não defendeu e limpou'), ('3', 'Não defendeu e não limpou'), ('4', 'Manifesto e julgamento fora do sistema'), ('5', 'Defendeu após o prazo e limpou'), ('6', 'Não recebeu e limpou'), ('7', 'Edital'), ('8', 'Não defendeu e não limpou via Edital'), ('9', 'Não defendeu e limpou via Edital')], max_length=25, null=True, verbose_name='Situação'),
        ),
    ]
