# Generated by Django 4.0 on 2022-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_alter_infracao_status_rastreio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='produtidade_inspecao',
            field=models.DateField(null=True, verbose_name='Qual o mês (data) da produtividade?'),
        ),
    ]
