# Generated by Django 4.0 on 2022-12-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0038_inspecao_produtidade_inspecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='infracao',
            name='produtividade_infracao',
            field=models.DateField(null=True, verbose_name='Qual o mês (data) da produtividade?'),
        ),
        migrations.AddField(
            model_name='infracao',
            name='produtividade_manifesto',
            field=models.DateField(null=True, verbose_name='Qual o mês (data) da produtividade do manifesto?'),
        ),
    ]
