# Generated by Django 4.0 on 2022-12-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0039_infracao_produtividade_infracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='produtividade_manifesto',
            field=models.DateField(blank=True, null=True, verbose_name='Qual o mês (data) da produtividade do manifesto?'),
        ),
    ]
