# Generated by Django 4.0 on 2022-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0040_alter_infracao_produtividade_manifesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='produtividade_infracao',
            field=models.DateField(blank=True, null=True, verbose_name='Qual o mês (data) da produtividade?'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='produtidade_inspecao',
            field=models.DateField(blank=True, null=True, verbose_name='Qual o mês (data) da produtividade?'),
        ),
    ]
