# Generated by Django 4.0 on 2023-01-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0041_alter_infracao_produtividade_infracao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infracao',
            options={'ordering': ['-id']},
        ),
    ]
