# Generated by Django 4.0 on 2023-01-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_alter_infracao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspecao',
            options={'ordering': ['-id']},
        ),
    ]
