# Generated by Django 4.0 on 2023-01-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0043_alter_inspecao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infracao',
            options={},
        ),
    ]
