# Generated by Django 4.0 on 2023-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_alter_infracao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='quadra',
            field=models.CharField(max_length=8),
        ),
    ]
