# Generated by Django 4.0 on 2023-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0045_alter_terreno_quadra'),
    ]

    operations = [
        migrations.AddField(
            model_name='infracao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
