# Generated by Django 4.1.7 on 2023-05-08 01:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Semana epidemiológica')),
                ('data_inicio_semana', models.DateField(verbose_name='Início')),
                ('data_fim_semana', models.DateField(verbose_name='Término')),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2100)])),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Paciente')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('numero_paciente', models.CharField(max_length=20, verbose_name='Número')),
                ('usf', models.CharField(blank=True, choices=[('USF Alvorada', 'USF Alvorada'), ('USF Asilo', 'USF Asilo'), ('USF Centro', 'USF Centro'), ('USF CAIC II', 'USF CAIC II'), ('USF CAIC III', 'USF CAIC III'), ('USF Cidade Industrial', 'USF Cidade Industrial'), ('EAP Rural', 'EAP Rural'), ('USF Estação', 'USF Estação'), ('USF Guardinha', 'USF Guardinha'), ('USF João XXIII', 'USF João XXIII'), ('USF Lagoinha', 'USF Lagoinha'), ('USF Jardim Planalto', 'USF Jardim Planalto'), ('USF San Genaro', 'USF San Genaro'), ('USF Santa Maria', 'USF Santa Maria'), ('USF São Judas', 'USF São Judas'), ('Unidade de Termópolis', 'Unidade de Termópolis'), ('USF Veneza', 'USF Veneza'), ('USF Verona', 'USF Verona'), ('USF Vila Formosa', 'USF Vila Formosa'), ('USF Vila Mariana', 'USF Vila Mariana')], max_length=35, null=True, verbose_name='USF')),
                ('data_recebimento', models.DateField()),
                ('notificadora', models.CharField(choices=[('USF Alvorada', 'USF Alvorada'), ('Ampara', 'Ampara'), ('USF Asilo', 'USF Asilo'), ('USF Centro', 'USF Centro'), ('USF CAIC II', 'USF CAIC II'), ('USF CAIC III', 'USF CAIC III'), ('USF Cidade Industrial', 'USF Cidade Industrial'), ('EAP Rural', 'EAP Rural'), ('USF Estação', 'USF Estação'), ('Farmácia Ana Terra', 'Farmácia Ana Terra'), ('USF Guardinha', 'USF Guardinha'), ('USF João XXIII', 'USF João XXIII'), ('Laboratório Athena', 'Laboratório Athena'), ('Laboratório Biolabory', 'Laboratório Biolabory'), ('Laboratório Hormossul', 'Laboratório Hormossul'), ('Laboratório JG', 'Laboratório JG'), ('Laboratório São Lucas', 'Laboratório São Lucas'), ('Laboratório Vitale', 'Laboratório Vitale'), ('USF Lagoinha', 'USF Lagoinha'), ('USF Jardim Planalto', 'USF Jardim Planalto'), ('USF San Genaro', 'USF San Genaro'), ('Santa Casa', 'Santa Casa'), ('USF Santa Maria', 'USF Santa Maria'), ('USF São Judas', 'USF São Judas'), ('Unidade de Termópolis', 'Unidade de Termópolis'), ('Unimed', 'Unimed'), ('UPA - Unidade de Pronto Atendimento', 'UPA - Unidade de Pronto Atendimento'), ('USF Veneza', 'USF Veneza'), ('USF Verona', 'USF Verona'), ('Vigilância em Saúde', 'Vigilância em Saúde'), ('USF Vila Formosa', 'USF Vila Formosa'), ('USF Vila Mariana', 'USF Vila Mariana')], max_length=50, verbose_name='Unidade notificadora')),
                ('data_notificacao', models.DateField(verbose_name='Data da notificação')),
                ('data_inicio_sintomas', models.DateField(verbose_name='Data de início dos sintomas')),
                ('data_limite_coleta', models.DateField(verbose_name='Data de limite da coleta')),
                ('sinan', models.PositiveIntegerField(blank=True, null=True, verbose_name='SINAN')),
                ('resultado', models.CharField(choices=[('Positivo NS1', 'Positivo NS1'), ('Positivo sorologia', 'Positivo sorologia'), ('Negativo NS1', 'Negativo NS1'), ('Negativo sorologia', 'Negativo sorologia'), ('Aguardando agendamento', 'Aguardando agendamento'), ('Aguardando coleta', 'Aguardando coleta'), ('Aguardando resultado', 'Aguardando resultado'), ('Faltou', 'Faltou'), ('Recusou', 'Recusou'), ('Isolamento viral positivo', 'Isolamento viral positivo'), ('Isolamento viral negativo', 'Isolamento viral negativo'), ('Não agendado', 'Não agendado')], max_length=40)),
                ('internacao', models.DateField(blank=True, null=True, verbose_name='Internação')),
                ('obito', models.DateField(blank=True, null=True, verbose_name='Óbito')),
                ('status_obito', models.CharField(blank=True, choices=[('Óbito confirmado', 'Óbito confirmado'), ('Óbito em investigação', 'Óbito em investigação'), ('Óbito descartado', 'Óbito descartado')], max_length=25, null=True, verbose_name='Status óbito')),
                ('data_agendamento', models.DateField(blank=True, null=True, verbose_name='Data de agendamento')),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observações')),
                ('logradouro_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.logradouro')),
                ('semana_epidemiologica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dengue.semana')),
            ],
        ),
    ]
