# Generated by Django 4.1.7 on 2023-05-08 01:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cnae', models.CharField(max_length=9)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contabilidade', models.CharField(max_length=40)),
                ('telefone1_contabilidade', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('telefone2_contabilidade', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2')),
                ('email_contabilidade', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato_contabilidade', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risco', models.CharField(max_length=45)),
                ('valor_risco', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nome Fantasia')),
                ('mei', models.BooleanField(verbose_name='MEI')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_empresa', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento_empresa', models.CharField(blank=True, max_length=40, null=True, verbose_name='Complemento')),
                ('responsavel_legal', models.CharField(max_length=60, verbose_name='Responsável legal')),
                ('rg_responsavel_legal', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cpf_responsavel_legal', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=60, null=True, verbose_name='Responsável Técnico')),
                ('cpf_responsavel_tecnico', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('conselho_responsavel_tecnico', models.CharField(blank=True, max_length=60, null=True, verbose_name='Conselho de classe')),
                ('alvara', models.DateField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observações')),
                ('status_funcionamento', models.CharField(choices=[('ATIVA', 'ATIVA'), ('BAIXADA', 'BAIXADA'), ('DISPENSADA', 'DISPENSADA')], max_length=20)),
                ('cnae', models.ManyToManyField(related_name='Cnae', to='empresas.cnae')),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.contabilidade')),
                ('logradouro_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.logradouro')),
                ('risco_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.risco')),
            ],
        ),
        migrations.AddField(
            model_name='cnae',
            name='risco_cnae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.risco'),
        ),
    ]
